package org.example.audio_ecommerce.entity.Enum;

public enum NotificationType {
    NEW_ORDER,
    ORDER_PAID,
    ORDER_CANCELLED,
    NEW_REVIEW,
    STOCK_LOW,
    WALLET_SETTLED,
    WALLET_RELEASE,
    NEW_REVIEW_REPLY,
    ORDER_CANCEL_APPROVED,
    ORDER_CANCEL_REJECTED,
    ORDER_CANCEL_REQUESTED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    RETURN_SHIPPING,
    RETURN_RESOLVED,
    RETURN_REFUNDED,
    RETURN_CANCELLED,
    RETURN_PACKAGE_SET,
    RETURN_ESCALATED
}
